### ISSUE TITLE
Chocolatey is not installed

### ISSUE THREAD

**Issue by nay-ta** [lukaszliniewicz/Pandrator#26]
INFO - Chocolatey is not installed.
INFO - Installing Chocolatey...
INFO - Installing calibre...

I can't do anything,
What should I do?
Why?
Can't I just use exe?

deepL

**Comment by Siddharth-Latthe-07** [comment]
@nay-ta , the problem seems to be looks like you're trying to install Calibre, and the process is attempting to use Chocolatey, which is a package manager for Windows. 
follow these steps and let me know, ifit works successfully
1. Use the .exe Installer: If you prefer not to use Chocolatey, you can directly download the .exe installer for Calibre from its official website and run it manually.
Go to the Calibre download page.
Select the version for Windows and download the .exe file.
Run the downloaded .exe file and follow the installation prompts

OR

Install Chocolatey Manually: If you want to proceed with the installation via Chocolatey, you might need to install Chocolatey manually first. Here’s how:
Open PowerShell as an administrator and

Run the following command to install Chocolatey:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```
After Chocolatey is installed, you can install Calibre using the following command:
```
choco install calibre
```
plz let me know, if it works or not
Thanks

**Comment by esvoaca** [comment]
@nay-ta just ran into a similar problem, but instead of calibre it was ffmpeg.

The issue was that I ran the .exe file first without admin privileges, it created the Chocolatey folder in C:\ProgramData and crashed.

I fixed it by going in ProgramData and deleting the folder, and run the .exe file again as admin. It's installing fine now
