### ISSUE TITLE
LLM Processing

### ISSUE THREAD

**Issue by JohnF51** [lukaszliniewicz/Pandrator#39]
Hi, so first of all a big thanks for the excellent work, very useful app. I admire how you managed to put it all together, I consider it a masterpiece :)

I would like to ask you how to use LLM Processing, when I give load LLM models it prints Failed connect to the LLM API error. I have all the API keys filled in. I am using XTTS model with CUDA. Does it make sense to use LLM with Czech language? And I also want to ask if you have come across Slovak language somewhere. I would need XTTS in Slovak language but I don't know how to train it since it is not supported in available languages. Thank you for your answer. Thank you for your excellent work.

**Comment by lukaszliniewicz** [comment]
I'm sorry, some features aren't as easy to use to as complete as I would like yet. Currently LLM processing of text can be done only via a local API (I've been using the API of the Text Generation WebUI). The proprietary models are only used for translating subtitles at the moment. I will add them to text processing as well, but it requires a bit of a redesign, because we should then pass larger fragments of texts, not single sentences, to save on prompt input tokens (and they are much more capable, so they can handle that). It should come reasonably soon(ish). As for Slovak, XTTS could be trained for it, but I haven't experimented with that yet. I will have a look and maybe there is a model that supports Slovak out of the box.

**Comment by lukaszliniewicz** [comment]
There is a way to train XTTS for a new language, but we would need a lot of good quality materials. such as audiobooks. If you have Discord, we can talk about that.

**Comment by JohnF51** [comment]
This is great unfortunately I don't have a dicord, and I'm poor at speaking English, but the writing is good. If you could help me and make some program to train the language via webui or through a graphical interface like tkinter. And how much data is needed to train the language? I record audiobooks myself. This is from my [youtube chanel] Pilgrim progress (https://www.youtube.com/watch?v=ccOayWVXy9E&list=PL6XUSwZPM69e1pdf-C50cWLLI56F4deVi) I can collect some data in Slovak language. Thank you.

**Comment by lukaszliniewicz** [comment]
You have a very nice voice! I'm not entirely sure how much audio is needed, but I will try to find out. I think certainly about 100h or so.

**Comment by lukaszliniewicz** [comment]
I could help you with the fine-tuning, just to see how well it works. How much good quality Slovak speech do you have, or can get (how many hours)?

**Comment by JohnF51** [comment]
That would be perfect. I'm still looking for and should have about 80 hours of quality recordings available. I am still working on it. Shall I collect this data and send it to you? Or can you help me write a script for vscode? Thank you
